// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/work.tsx";
import * as $3 from "./routes/work/[id].tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/work.tsx": $2,
    "./routes/work/[id].tsx": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
